## Pytorch 00

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
## Introduction to tensors

#Scalar tensor
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.item()

7

In [4]:
scalar.ndim #ndim = n dimensions

0

In [5]:
#Vector
vector = torch.tensor([7,8])
vector

tensor([7, 8])

In [6]:
vector.shape

torch.Size([2])

In [7]:
# Matrix 2 dimentional vector
MATRIX = torch.tensor([[2,3],[4,5]])
MATRIX

tensor([[2, 3],
        [4, 5]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX[1,0]

tensor(4)

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
#TENSOR n dimensional matrix
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape # 1 3x3 tensor

torch.Size([1, 3, 3])

In [14]:
## Random tensors
##Create a random tensor of size (3,4)

random_tansor = torch.rand(3,4)
random_tansor

tensor([[0.2781, 0.5066, 0.5234, 0.8674],
        [0.4908, 0.3832, 0.8803, 0.3234],
        [0.0793, 0.0810, 0.3157, 0.5027]])

In [15]:
random_tansor.ndim

2

In [16]:
##Create a random tensor similar to an image tensor
random_image_tensor = torch.rand(size=(224,224,3)) #Height width, color(RGB)
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [17]:
#Binary tensor
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
zeros*random_tansor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

In [21]:
#Create a range of tensors
range_tensor = torch.arange(3,10,2) #start, end, step
range_tensor

tensor([3, 5, 7, 9])

In [22]:
#Creating tensor like
copy_of_range_zeros = torch.zeros_like(range_tensor) #Ayni tensorun sifirlisi
copy_of_range_zeros

tensor([0, 0, 0, 0])

In [23]:
#Tensor Datatypes
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None, #GPU,cuda etc
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [24]:
float_32_tensor.dtype

torch.float32

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [26]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [27]:
#Type of the product
(float_16_tensor*float_32_tensor).dtype


torch.float32

In [28]:
#Get information from tensors

some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5647, 0.8646, 0.3881, 0.1417],
        [0.1605, 0.8793, 0.8760, 0.2057],
        [0.6668, 0.1473, 0.8786, 0.1435]])

In [29]:
#Find the details
print(some_tensor)
print(f"Shape of tensor is {some_tensor.shape}")
print(f"Data type is {some_tensor.dtype}")
print(f"Data device is {some_tensor.device}")

tensor([[0.5647, 0.8646, 0.3881, 0.1417],
        [0.1605, 0.8793, 0.8760, 0.2057],
        [0.6668, 0.1473, 0.8786, 0.1435]])
Shape of tensor is torch.Size([3, 4])
Data type is torch.float32
Data device is cpu


In [30]:
#Manipulating tensors

#Addition/Substraction
tensor = torch.tensor([1,2,3])
print(tensor + 10)

#Multiply
print(tensor * 10)


tensor([11, 12, 13])
tensor([10, 20, 30])


In [31]:
#Matrix Multiplication(dot product)
%%time
first_t = torch.tensor([[1,2,3],[2,3,4]])
second_t = torch.tensor([[1,5,6],[1,4,5],[1,5,2]])

torch.matmul(first_t,second_t) #2x3 . 3x3 = 2x3 # "@" sembolu de kullanilabilir

CPU times: user 1.24 ms, sys: 85 µs, total: 1.32 ms
Wall time: 17.6 ms


tensor([[ 6, 28, 22],
        [ 9, 42, 35]])

In [32]:
#Transpose
tensor = torch.rand(2,3)
print(tensor)
print(tensor.shape)
print()

print(f"The transpose of it is: {tensor.T}")
print(tensor.T.shape)

tensor([[0.5414, 0.6153, 0.3039],
        [0.0409, 0.9293, 0.3210]])
torch.Size([2, 3])

The transpose of it is: tensor([[0.5414, 0.0409],
        [0.6153, 0.9293],
        [0.3039, 0.3210]])
torch.Size([3, 2])


In [33]:
#Find min max

x = torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [34]:
print(torch.min(x)) #or could use x.min()
print(x.max())
#print(torch.max(x))
print(torch.mean(x.type(torch.float32))) #64 ile calismiyor
print(torch.sum(x.type(torch.float32)))

tensor(1)
tensor(91)
tensor(46.)
tensor(460.)


In [35]:
#Find psoition of min max
print(x.argmin())
print(x.argmax())

tensor(0)
tensor(9)


In [36]:
#Reshaping, view , stacking squeezing, unsqueezing, permute
x = torch.arange(1.,11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [37]:
#Add extra dimension (Reshaping)

x_reshaped = x.reshape(1,10) #Burda 1D olan tensoru 2Dye geciriyoruz
print(x_reshaped, x.shape)
print()
x_reshaped = x.reshape(10,1)
print(x_reshaped, x.shape)


tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]) torch.Size([10])

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]]) torch.Size([10])


In [38]:
#Reshaping

x_reshaped = x.reshape(5,2) #10luk veriyi 2li paketledim burda veri saisi tuttugu icin bunu yapabiliyorum
x_reshaped

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [39]:
#View
z = x.view(1,10)

#Changing z changes x "hardcopy"
z = x.reshape(5,2)
z[:,0] = 5
x

tensor([ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.])

In [40]:
#Stack
print(x)

x_stacked = torch.stack([x,x,x], dim=0) #Ust uste koy
print(x_stacked)
print()
x_stacked = torch.stack([x,x,x], dim=1) #Yan yana koy
print(x_stacked)

tensor([ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.])
tensor([[ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.],
        [ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.],
        [ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.]])

tensor([[ 5.,  5.,  5.],
        [ 2.,  2.,  2.],
        [ 5.,  5.,  5.],
        [ 4.,  4.,  4.],
        [ 5.,  5.,  5.],
        [ 6.,  6.,  6.],
        [ 5.,  5.,  5.],
        [ 8.,  8.,  8.],
        [ 5.,  5.,  5.],
        [10., 10., 10.]])


In [41]:
#Squeeze
x_reshaped = x.reshape(1,10)

print(x_reshaped)
print(x_reshaped.shape)
print()
x_squeezed = x_reshaped.squeeze()
print(x_squeezed)
print(x_squeezed.shape)

tensor([[ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.]])
torch.Size([1, 10])

tensor([ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.])
torch.Size([10])


In [42]:
#Unsqueeze

print(x_squeezed)
print(x_squeezed.shape)
print()
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(x_unsqueezed)
print(x_unsqueezed.shape)
print()
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(x_unsqueezed)
print(x_unsqueezed.shape)

tensor([ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.])
torch.Size([10])

tensor([[ 5.,  2.,  5.,  4.,  5.,  6.,  5.,  8.,  5., 10.]])
torch.Size([1, 10])

tensor([[ 5.],
        [ 2.],
        [ 5.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 5.],
        [ 8.],
        [ 5.],
        [10.]])
torch.Size([10, 1])


In [43]:
#Permute - rearrange the dimensions of a target tensor in a specific order

x_image = torch.rand((224,220,3)) #Height, width, color channels

#Permute the tensor as color, height, width
x_permuted = x_image.permute(2,0,1) #Ilk hangisi gelsin seklinde calisiyo
x_permuted.shape

torch.Size([3, 224, 220])

In [44]:
#Permuted view kullaniyo yani hardcopy, bi degeri degistirirsen hardcopyden de degisir

x_image[0,0,0] = 10
print(f"First element of x_image changed to {x_image[0,0,0]}")
print(f"So the x_permuted first element also changed to {x_permuted[0,0,0]}")

First element of x_image changed to 10.0
So the x_permuted first element also changed to 10.0


In [45]:
#Indexing
x = torch.arange(1,10).reshape(1,3,3)  #3 dimension
print(f"x is: {x} with size {x.shape}")

x is: tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]) with size torch.Size([1, 3, 3])


In [46]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [47]:
#x[0,1] or
x[0][1]

tensor([4, 5, 6])

In [48]:
x[0,1,2]

tensor(6)

In [49]:
# Use : to select all colomnn
print(f"Selecting the first elements: {x[0,:,0]}")

Selecting the first elements: tensor([1, 4, 7])


In [50]:
#Get all values of 0th and 1st dimensions but only index 1 of second dim
x[:,:,1]

tensor([[2, 5, 8]])

In [51]:
# Pytorch tensors ad Numpy
import torch
import numpy as np

In [52]:
array = np.arange(1.0,8.0)
#Changing numpy to tensor
tensor = torch.from_numpy(array)#.type(torch.float32) for default
array, tensor
#Note: It changes to float64 which is not the default in pytorch

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [53]:
#Change in the array reflects to the tensor "Hardcopy"
array[0] = 5
array, tensor

(array([5., 2., 3., 4., 5., 6., 7.]),
 tensor([5., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [54]:
#Change tensor to numpy

tensor = torch.randint(0,10,(2,5))
print(tensor)

numpy_tensor = tensor.numpy()
print(numpy_tensor)

tensor([[6, 7, 8, 0, 1],
        [2, 7, 3, 8, 6]])
[[6 7 8 0 1]
 [2 7 3 8 6]]


In [55]:
tensor[0,0] = 10
print(tensor)
print("It also changes the numpy")
print(numpy_tensor)

tensor([[10,  7,  8,  0,  1],
        [ 2,  7,  3,  8,  6]])
It also changes the numpy
[[10  7  8  0  1]
 [ 2  7  3  8  6]]


In [56]:
# Reproducibility - seed in randomness

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)
print(random_tensor_A)
torch.manual_seed(RANDOM_SEED) #Her seferide ayarlaman lazim
random_tensor_B = torch.rand(3,4)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [57]:
!nvidia-smi

Wed Aug  5 07:59:26 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   54C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [58]:
# Check for GPU access
torch.cuda.is_available()

True

In [59]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [60]:
# Putting tensors on the GPU

tensor = torch.tensor([1,2,3])
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [61]:
#Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [62]:
# Move tensors back to cpu, Numpy cant run on GPU
tensor_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_on_cpu, tensor_on_cpu.device

(array([1, 2, 3]), 'cpu')